### ISSUE TITLE
missing schematics

### ISSUE THREAD

**Issue by pabigot** [particle-iot/boron#2]
The argon and xenon repositories have the schematics in PDF form.  Would it be feasible to add them for boron as well?

**Comment by rickkas7** [comment]
Sure. I just added the Boron schematic in pdf format in the pdfs directory.

**Comment by jacky4566** [comment]
Hate to nag but can we get the PDF in a searchable format. It can be difficult to find rails and pins otherwise. 
Adobe OCR seems to fail on that pdf.
